Update terraform-pipeline.yml

diff --git a/.github/workflows/terraform-pipeline.yml b/.github/workflows/terraform-pipeline.yml
--- a/.github/workflows/terraform-pipeline.yml
+++ b/.github/workflows/terraform-pipeline.yml
@@ -159,16 +159,18 @@ jobs:
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
           aws configure set region $TF_VAR_aws_region
-          
+
       - name: Select Subnet and Create Security Group
         run: |
+          # Seleccionar la primera subnet de la lista
           SUBNET_ID=$(echo '${{ needs.terraform-deploy.outputs.private_subnet_ids }}' | jq -r '.[0]')
-          
+
           if [ -z "$SUBNET_ID" ]; then
             echo "Error: SUBNET_ID is empty or not defined"
             exit 1
           fi
 
+          # Comprobar si el Security Group ya existe
           SECURITY_GROUP_ID=$(aws ec2 describe-security-groups \
             --filters Name=group-name,Values=github-runner-sg Name=vpc-id,Values=${{ needs.terraform-deploy.outputs.vpc_id }} \
             --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || true)
@@ -181,9 +183,10 @@ jobs:
               --query 'GroupId' --output text)
           fi
 
+          # Comprobar y configurar reglas de ingreso para puerto 443
           EXISTS_443=$(aws ec2 describe-security-groups \
             --group-ids $SECURITY_GROUP_ID \
-            --query "SecurityGroups[0].IpPermissions[?FromPort==`443` && ToPort==`443`].UserIdGroupPairs[?GroupId=='$SECURITY_GROUP_ID']" \
+            --query "SecurityGroups[0].IpPermissions[?FromPort==443 && ToPort==443].UserIdGroupPairs[?GroupId=='$SECURITY_GROUP_ID']" \
             --output text)
 
           if [ -z "$EXISTS_443" ]; then
@@ -194,9 +197,10 @@ jobs:
               --source-group $SECURITY_GROUP_ID
           fi
 
+          # Comprobar y configurar reglas de ingreso para puerto 22
           EXISTS_22=$(aws ec2 describe-security-groups \
             --group-ids $SECURITY_GROUP_ID \
-            --query "SecurityGroups[0].IpPermissions[?FromPort==`22` && ToPort==`22`].IpRanges[?CidrIp=='0.0.0.0/0']" \
+            --query "SecurityGroups[0].IpPermissions[?FromPort==22 && ToPort==22].IpRanges[?CidrIp=='0.0.0.0/0']" \
             --output text)
 
           if [ -z "$EXISTS_22" ]; then
@@ -224,6 +228,7 @@ jobs:
           ./svc.sh start
           EOF
           )
+
           INSTANCE_ID=$(aws ec2 run-instances \
             --image-id ami-0dba2cb6798deb6d8 \
             --count 1 \
@@ -235,4 +240,10 @@ jobs:
             --query 'Instances[0].InstanceId' \
             --output text)
 
+          if [ -z "$INSTANCE_ID" ]; then
+            echo "Error: EC2 instance creation failed"
+            exit 1
+          fi
+
           aws ec2 wait instance-status-ok --instance-ids $INSTANCE_ID
+          echo "Instance $INSTANCE_ID is ready."
